# scGPT — model-specific configuration

model_name: scGPT

preprocessing:
  filter_gene_by_counts: 400
  filter_cell_by_counts: 100
  normalize_total: 10000.0
  log1p: true
  subset_hvg: false

model: {}

dataloader:
  batch_size: 64
  num_workers: 0
  seed: 0

training:
  gep:
    mask_prob: 0.15

resources:
  model_file: "{resource_dir}/scGPT/best_model.pt"
  vocab_file: "{resource_dir}/scGPT/vocab.json"
